version: '3.8'

services:
  myapp:
    image: "myapp:1"
    ports:
      - "8080:5000"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:17-alpine"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: ghatraining
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - db_password
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ghatraining"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

secrets:
  db_password:
    file: ./secrets/db_password.txt

volumes:
  pgdata:
