name: Build and Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app
        run: |
          export FLASK_PORT=5000
          python app/main.py &
          sleep 5

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Call /books endpoint
        run: |
          curl --fail http://localhost:8080/books
