name: Build and Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create secrets file
        run: |
          mkdir -p secrets
          echo "secret_password" > secrets/db_password.txt

      - name: Build myapp image
        run: |
          docker build -t myapp:1 .

      - name: Starts app with compose
        run: |
          docker compose up

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Call /books endpoint
        run: |
          curl --fail http://localhost:8080/books
